
vim.cmd 'packadd nvim-lspconfig'
vim.cmd 'packadd snacks.nvim'
vim.cmd 'packadd mini.icons'
vim.cmd 'packadd nvim-web-devicons'
vim.cmd 'packadd gitsigns.nvim'
vim.cmd 'packadd fzf-lua'
vim.cmd 'packadd which-key.nvim'
vim.cmd 'packadd stay-centered.nvim'
vim.cmd 'packadd outline.nvim'

vim.cmd 'packadd lazygit.nvim'
vim.cmd 'packadd plenary.nvim'
vim.cmd 'packadd telescope.nvim'
vim.cmd 'packadd telescope-fzf-native.nvim'
vim.cmd 'packadd telescope-file-browser.nvim'
vim.cmd 'packadd telescope-undo.nvim'
vim.cmd 'packadd bufferline.nvim'
vim.cmd 'packadd toggleterm.nvim'

vim.cmd 'packadd everforest'
vim.cmd 'packadd gruvbox'
vim.cmd 'packadd kanagawa.nvim'
vim.cmd 'packadd material.vim'
vim.cmd 'packadd onedark.vim'
vim.cmd 'packadd tokyonight.nvim'
